name: Release Cutoff Enforcement and Notification

on:
  push:
    branches:
      - 'release/*'

jobs:
  release-cutoff-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python and dependencies
        run: pip install pyyaml

      - name: Write cutoff script
        run: |
          cat << 'EOF' > cutoff_script.py
          import os
          import yaml
          
          branch = os.environ.get('BRANCH_NAME')
          try:
              with open('.release_config.yml', 'r') as f:
                  config = yaml.safe_load(f)
              cutoff = config['releases'].get(branch, {}).get('cutoff', None)
          except Exception as e:
              cutoff = None
          
          if cutoff:
              print(f'cutoff={cutoff}')
          else:
              print('cutoff=9999-99-99')
          EOF

      - name: Read cutoff from metadata file
        id: cutoff
        run: |
          output=$(python cutoff_script.py)
          echo "$output" >> $GITHUB_OUTPUT
        env:
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Check cutoff and set result
        id: check
        run: |
          NOW=$(date +%Y-%m-%d)
          CUTOFF="${{ steps.cutoff.outputs.cutoff }}"
          echo "Current date: $NOW"
          echo "Cutoff date: $CUTOFF"
          if [ "$CUTOFF" == "9999-99-99" ]; then
            echo "notify=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          if [[ "$NOW" > "$CUTOFF" ]]; then
            echo "notify=true" >> $GITHUB_OUTPUT
            echo "CI/CD blocked: commit after cutoff $CUTOFF."
            exit 1
          else
            echo "notify=false" >> $GITHUB_OUTPUT
            echo "CI/CD allowed: commit before cutoff $CUTOFF."
          fi

      - name: Send notification email if blocked
        if: failure() && steps.check.outputs.notify == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "CI/CD Blocked for Release Branch"
          body: |
            [Automated Notice]
            A commit was made to release branch '${{ github.ref_name }}' after cutoff date ${{ steps.cutoff.outputs.cutoff }}.
            CI/CD has been blocked. Please review!
          to: "z.ajmal759@gmail.com"
          from: "z.ajmal759@gmail.com"

      - name: Run CI/CD steps
        if: success()
        run: echo "Running CI/CD for release branch."
