name: Release Cutoff Enforcement and Notification

on:
  push:
    branches:
      - 'release/*'

jobs:
  release-cutoff-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python and dependencies
        run: pip install pyyaml

      - name: Write cutoff script
        run: |
          cat << 'EOF' > cutoff_script.py
          import os
          import yaml
          
          branch = os.environ.get('BRANCH_NAME')
          try:
              with open('.release_config.yml', 'r') as f:
                  config = yaml.safe_load(f)
              cutoff = config['releases'].get(branch, {}).get('cutoff', None)
          except Exception as e:
              cutoff = None
          
          if cutoff:
              print(f'cutoff={cutoff}')
          else:
              print('cutoff=9999-99-99')
          EOF

      - name: Read cutoff from metadata file
        id: cutoff
        run: |
          output=$(python cutoff_script.py)
          cutoff_date=$(echo "$output" | grep 'cutoff=' | cut -d '=' -f2)
          echo "cutoff=$cutoff_date" >> $GITHUB_OUTPUT
        env:
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Get commit date and check cutoff
        id: check
        run: |
          COMMIT_DATE=$(git show -s --format=%cd --date=format:%Y-%m-%d ${{ github.sha }})
          CUTOFF="${{ steps.cutoff.outputs.cutoff }}"

          COMMIT_TS=$(date -d "$COMMIT_DATE" +%s)
          CUTOFF_TS=$(date -d "$CUTOFF" +%s)

          echo "Commit date: $COMMIT_DATE"
          echo "Cutoff date: $CUTOFF"
          echo "Commit timestamp: $COMMIT_TS"
          echo "Cutoff timestamp: $CUTOFF_TS"

          if [ "$CUTOFF" == "9999-99-99" ]; then
            echo "notify=false" >> $GITHUB_OUTPUT
            echo "proceed_with_cicd=true" >> $GITHUB_OUTPUT
            echo "block_workflow=false" >> $GITHUB_OUTPUT
            echo "No cutoff date configured - proceeding with CI/CD"
          elif [ "$COMMIT_TS" -gt "$CUTOFF_TS" ]; then
            echo "notify=true" >> $GITHUB_OUTPUT
            echo "proceed_with_cicd=false" >> $GITHUB_OUTPUT
            echo "block_workflow=true" >> $GITHUB_OUTPUT
            echo "CI/CD blocked: commit made after cutoff $CUTOFF (commit date: $COMMIT_DATE)."
          else
            echo "notify=false" >> $GITHUB_OUTPUT
            echo "proceed_with_cicd=true" >> $GITHUB_OUTPUT
            echo "block_workflow=false" >> $GITHUB_OUTPUT
            echo "CI/CD allowed: commit made before cutoff $CUTOFF (commit date: $COMMIT_DATE)."
          fi

      - name: Create blocking issue when CI/CD is blocked
        if: steps.check.outputs.notify == 'true'
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: "🚫 CI/CD Blocked: Release Branch Past Cutoff (${{ github.ref_name }})"
          body: |
            ## 🚫 CI/CD Blocked - Release Branch Past Cutoff
            
            **⚠️ AUTOMATIC BLOCK TRIGGERED**
            
            ### Details
            - **Branch:** `${{ github.ref_name }}`
            - **Cutoff Date:** `${{ steps.cutoff.outputs.cutoff }}`
            - **Commit Date:** `$(git show -s --format=%cd --date=format:%Y-%m-%d ${{ github.sha }})`
            - **Commit SHA:** `${{ github.sha }}`
            - **Author:** `@${{ github.actor }}`
            - **Triggered by:** [Workflow Run #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            ### What Happened?
            A commit was made on `$(git show -s --format=%cd --date=format:%Y-%m-%d ${{ github.sha }})` and pushed to release branch `${{ github.ref_name }}` after the established cutoff date of **${{ steps.cutoff.outputs.cutoff }}**.
            
            The CI/CD pipeline has been **automatically blocked** to prevent uncontrolled changes to this release.
            
            ### Required Actions
            - [ ] **Review the urgency** of this commit with the release manager
            - [ ] **Get approval** from stakeholders for post-cutoff changes
            - [ ] **Verify impact** on release timeline and stability
            - [ ] **Update cutoff date** in `.release_config.yml` if needed (emergency only)
            - [ ] **Close this issue** once resolved
            
            ### Emergency Override
            If this is a critical hotfix, update the cutoff date in `.release_config.yml`:
            ```yaml
            releases:
              ${{ github.ref_name }}:
                cutoff: "NEW_DATE_HERE"  # Format: YYYY-MM-DD
            ```
            
            ---
            _This issue was automatically created by the Release Cutoff Enforcement workflow._
          assignees: |
            shani759
          labels: |
            release-cutoff
            blocked
            urgent

      - name: Add comment to triggering commit
        if: steps.check.outputs.notify == 'true'
        uses: peter-evans/commit-comment@v3
        with:
          token: ${{ github.token }}
          sha: ${{ github.sha }}
          body: |
            🚫 **CI/CD BLOCKED** - This commit was made after the release cutoff date (**${{ steps.cutoff.outputs.cutoff }}**).
            
            **Commit Date:** `$(git show -s --format=%cd --date=format:%Y-%m-%d ${{ github.sha }})`
            
            A [blocking issue has been created](https://github.com/${{ github.repository }}/issues) for review.
            
            Please contact the release manager before proceeding.

      - name: Block workflow if past cutoff
        if: steps.check.outputs.block_workflow == 'true'
        run: |
          echo "🚫 Workflow blocked - commit made after cutoff date"
          exit 1

      - name: Run CI/CD steps
        if: steps.check.outputs.proceed_with_cicd == 'true'
        run: echo "✅ Running CI/CD for release branch - commit made before cutoff date."
