name: Update CODEOWNERS File

on:
  create:
    branches:
      - 'release/*'
      - 'releases/*'

jobs:
  update-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout new branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create update branch
        run: |
          BRANCH_NAME="update-codeowners-$(date +%s)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME

      - name: Copy release CODEOWNERS file
        run: |
          cp .github/CODEOWNERS.release .github/CODEOWNERS
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/CODEOWNERS
          git commit -m "Update CODEOWNERS for release branch"

      - name: Push update branch
        run: |
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: ${{ github.ref_name }}
          title: "Update CODEOWNERS for release branch ${{ github.ref_name }}"
          body: |
            This PR automatically updates the CODEOWNERS file for the release branch.
            
            Changes:
            - Copied `.github/CODEOWNERS.release` to `.github/CODEOWNERS`
            
            This was triggered by the creation of branch: `${{ github.ref_name }}`
          delete-branch: true
