name: Update CODEOWNERS for Release Branch

on:
  create

jobs:
  update-codeowners-on-release-branch:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref_type == 'branch' && startsWith(github.event.ref, 'release/') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}

      - name: Create Release CODEOWNERS File
        run: |
          mkdir -p .github
          echo "* @spglobal-innersource/release-shepherds" > .github/CODEOWNERS

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/shani759/<repo>.git
          git push origin HEAD:release/my-feature

